# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,d296a13f1545e3a602a863fb1c4a41a245014cb5)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,8def90d911db66f9778787db39e25044574a7eee)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,0944434e964c88b3e709b3805873b1716a086c96)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,87192a46aad858073a74ab469424f57d85d05a00)
$(call add-radio-file-sha1-checked,radio/dpm.img,25297bb95d6f303eed6771c1f680a2fc1cd7ecbc)
$(call add-radio-file-sha1-checked,radio/gz.img,464b175f842f9dbe96027b434615f3f260251d18)
$(call add-radio-file-sha1-checked,radio/lk.img,f929f00d97e2c66e2ec8f422cbc3e245a32671ea)
$(call add-radio-file-sha1-checked,radio/logo.img,0b54247b3017dc685c6f032b4617b49f0f57f6c5)
$(call add-radio-file-sha1-checked,radio/mcupm.img,b84ad3188bec6b0b6507c939f522e33e3c4a9d3e)
$(call add-radio-file-sha1-checked,radio/md1img.img,caf751d8e593bdb2304fe7b846f61cd8aae3a484)
$(call add-radio-file-sha1-checked,radio/pi_img.img,304da4c37eed6ff8b3d8d50cd246abd296699a5b)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,0c78478ae51de3625fc680636835a83814f3ddc3)
$(call add-radio-file-sha1-checked,radio/scp.img,1e69b93247ec38891a86ff736473ae5cf3731859)
$(call add-radio-file-sha1-checked,radio/spmfw.img,29db4834e852935e241a6bca595efd0183012981)
$(call add-radio-file-sha1-checked,radio/sspm.img,72b90dadbd5c4a2a6658cdf24662b8ee7d7c0685)
$(call add-radio-file-sha1-checked,radio/tee.img,6f69d78c834fbabd0d16573bff32fc9d9e011ee1)

endif
