# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,f0bdedd42c55dce632d7691274879c8574b7631e)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,104c1d0f268469cfe172b30ecaa0de00bb1d6084)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,cc1a5df5e62177cc397b46348abaf355496fe309)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,1e1019975d34777a54c69f4e32ae2dd78a83aefa)
$(call add-radio-file-sha1-checked,radio/dpm.img,8cd821d9036781b9e06025d041c8c26e77b197be)
$(call add-radio-file-sha1-checked,radio/gz.img,b7f33e4e6fbae8902828338c6d06ac695fc7076d)
$(call add-radio-file-sha1-checked,radio/lk.img,b5e226a7fd1023dae489fd531cb36b9c07c67aef)
$(call add-radio-file-sha1-checked,radio/logo.img,607972328dd4e717b01278e60e11877b8386d9e4)
$(call add-radio-file-sha1-checked,radio/mcupm.img,ddf805c597ee6edd17a5f388437bc73491e63e14)
$(call add-radio-file-sha1-checked,radio/md1img.img,c2aadcb53543a8ba00e5264f7a405b4d14e85a59)
$(call add-radio-file-sha1-checked,radio/pi_img.img,285fd7255713cf2517ac0a139b5044fa1444b395)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,0d67218e5627a4af08c69890ec503f07fa1b2b4e)
$(call add-radio-file-sha1-checked,radio/scp.img,0ed39e134936746c6d853e221241daee53510112)
$(call add-radio-file-sha1-checked,radio/spmfw.img,ec15d5f1d39c9ce0608e0fa2bb41a1920441c7ef)
$(call add-radio-file-sha1-checked,radio/sspm.img,732662a977bee2c51de1f1012535cf59a2f2ffe8)
$(call add-radio-file-sha1-checked,radio/tee.img,e0b9bd830533ad66929973bf3486b319466d92dd)

endif
