# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,b40c22221159a72e0065bb92f272de2e6701efb5)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,fdfa5951b9d2c266dbeb7c864c12543708c2ec1c)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,dd5ec6ca7b6abb3c8e92356b095fd1cafca50036)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,03ee59dfc8b34c0d9d2a50629908176772ca149f)
$(call add-radio-file-sha1-checked,radio/dpm.img,6b17bf98bce116f8febab2fb4d5550d51c043947)
$(call add-radio-file-sha1-checked,radio/gz.img,cb8a2ee07cfd2ed4d799dee588395100572a26ac)
$(call add-radio-file-sha1-checked,radio/lk.img,39a11fbaf6eca28259eadd4955354291bffc7c32)
$(call add-radio-file-sha1-checked,radio/logo.img,4e523d8ce2dfeb38b9758fc7c4a158ca9ed2335c)
$(call add-radio-file-sha1-checked,radio/mcupm.img,9beb0b93094a5f9b045d0584094b72bab8e01607)
$(call add-radio-file-sha1-checked,radio/md1img.img,ef189a991c749bab0b56107d3a915cb89e6e48d7)
$(call add-radio-file-sha1-checked,radio/pi_img.img,c5146ac719fc66e662a4aef093df40523a78f089)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,a43daa6908ca61df23f122af90f561ac139379d8)
$(call add-radio-file-sha1-checked,radio/scp.img,4f0442656aa2a7b1bbceb1e87a3f4f14f416b7c6)
$(call add-radio-file-sha1-checked,radio/spmfw.img,79e67a30b98657df28c53dd3c0b2b07b08da1b6b)
$(call add-radio-file-sha1-checked,radio/sspm.img,c646d971b27a0dcbe274c948e811ed8087b960bf)
$(call add-radio-file-sha1-checked,radio/tee.img,66fd6cb05f8c08abdc192f66e4626a95b3333f83)

endif
